#
# Module manifest for module 'LibreDevOpsHelpers'
#
# Generated by: Craig Thacker
#
# Generated on: 23/03/2024
#

@{

# Script module or binary module file associated with this manifest.
    RootModule = '.\LibreDevOpsHelpers.psm1'

    # Version number of this module.
    ModuleVersion = '1.1.1'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID = '62141f8c-60b9-4bea-9a20-fee75504039c'

    # Author of this module
    Author = 'Craig Thacker'

    # Company or vendor of this module
    CompanyName = 'Libre DevOps'

    # Copyright statement for this module
    Copyright = '(c) Craig Thacker. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Helper functions for Libre DevOps projects'

    # Minimum version of the PowerShell engine required by this module
    # PowerShellVersion = ''

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @(
        'LibreDevOpsHelpers.AzureCli/LibreDevOpsHelpers.AzureClilogin.psm1',
        'LibreDevOpsHelpers.AzureDevOps/LibreDevOpsHelpers.AzureDevOps.psm1',
        'LibreDevOpsHelpers.AzureFunctionApps/LibreDevOpsHelpers.AzureFunctionApps.psm1',
        'LibreDevOpsHelpers.AzureKeyVault/LibreDevOpsHelpers.AzureKeyVault.psm1',
        'LibreDevOpsHelpers.AzureNsg/LibreDevOpsHelpers.AzureNsg.psm1',
        'LibreDevOpsHelpers.AzurePowerShell/LibreDevOpsHelpers.AzurePowerShell.psm1',
        'LibreDevOpsHelpers.AzureStorage/LibreDevOpsHelpers.AzureStorage.psm1',
        'LibreDevOpsHelpers.Checkov/LibreDevOpsHelpers.Checkov.psm1',
        'LibreDevOpsHelpers.Choco/LibreDevOpsHelpers.Choco.psm1',
        'LibreDevOpsHelpers.Docker/LibreDevOpsHelpers.Docker.psm1',
        'LibreDevOpsHelpers.Github/LibreDevOpsHelpers.Github.psm1',
        'LibreDevOpsHelpers.Homebrew/LibreDevOpsHelpers.Homebrew.psm1',
        'LibreDevOpsHelpers.Logger/LibreDevOpsHelpers.Logger.psm1',
        'LibreDevOpsHelpers.Packer/LibreDevOpsHelpers.Packer.psm1',
        'LibreDevOpsHelpers.Pester/LibreDevOpsHelpers.Pester.psm1',
        'LibreDevOpsHelpers.Python/LibreDevOpsHelpers.Python.psm1',
        'LibreDevOpsHelpers.Tenv/LibreDevOpsHelpers.Tenv.psm1',
        'LibreDevOpsHelpers.Terraform/LibreDevOpsHelpers.Terraform.psm1',
        'LibreDevOpsHelpers.Terraform.AzureImport/LibreDevOpsHelpers.Terraform.AzureImport.psm1',
        'LibreDevOpsHelpers.TerraformDocs/LibreDevOpsHelpers.TerraformDocs.psm1',
        'LibreDevOpsHelpers.Trivy/LibreDevOpsHelpers.Trivy.psm1',
        'LibreDevOpsHelpers.Utils/LibreDevOpsHelpers.Utils.psm1'
    )


    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = '*'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = '*'

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    # LibreDevOpsHelpers.psd1  – only the PrivateData → PSData block shown

    PrivateData = @{
        PSData = @{

            ReadmeFile = 'https://raw.githubusercontent.com/libre-devops/powershell-helpers/refs/heads/main/README.md'
            LicenseUri = 'https://raw.githubusercontent.com/libre-devops/powershell-helpers/main/LICENSE'
            ProjectUri = 'https://github.com/libre-devops/powershell-helpers'
            IconUri = 'https://libredevops.org/favicon.ico'

            Tags = 'terraform', 'devops', 'azure', 'checkov', 'helpers'
            ReleaseNotes = 'See CHANGELOG.md for full details'
        }
    }
}

