name: Run Docker – Windows Server Core 2022
################################################################################
# TRIGGERS
################################################################################
on:
  # Build automatically when any *.psd1 file is pushed to main
  push:
    branches: [ main ]
    paths:    [ '**/*.psd1' ]

  # Build automatically at 00:00 UTC on the 1 st of every month
  schedule:
    - cron: '0 0 1 * *'

  # Manual run
  workflow_dispatch:
    inputs:
      working_directory:
        description: 'Working directory passed to the script'
        type: string
        default: 'containers/windows-server2022'

      build_context:
        description: 'Docker build context'
        type: string
        default: 'github_workspace'

      docker_image_name:
        description: 'Docker image name (repo/name)'
        type: string
        default: 'powershell-helpers/windowsserver2022'

      enable_debug_mode:
        description: 'Enable -DebugMode in the script'
        type: boolean
        default: false

      registry_url:
        description: 'Container registry URL'
        type: string
        default: 'ghcr.io'

      docker_file_name:
        description: 'Dockerfile name'
        type: string
        default: 'Dockerfile'

      push_docker_image:
        description: 'Push image after build?'
        type: string          # Run-Docker.ps1 expects a *string* “true/false”
        default: 'true'

################################################################################
# JOBS
################################################################################
jobs:
  run-script:
    name: Run Build Script (Windows)
    runs-on: windows-latest          # <-- Windows runner

    defaults:
      run:
        shell: pwsh

    ########################
    # 1.  Resolve defaults #
    ########################
    env:
      WD_INPUT:      ${{ github.event.inputs.working_directory     || 'containers/windows-server2022' }}
      CTX_INPUT:     ${{ github.event.inputs.build_context         || 'github_workspace'               }}
      IMG_INPUT:     ${{ github.event.inputs.docker_image_name     || 'powershell-helpers/windowsserver2022' }}
      DEBUG_INPUT:   ${{ github.event.inputs.enable_debug_mode     || 'false'  }}
      PUSH_INPUT:    ${{ github.event.inputs.push_docker_image     || 'true'   }}
      DFNAME_INPUT:  ${{ github.event.inputs.docker_file_name      || 'Dockerfile' }}
      REGURL_INPUT:  ${{ github.event.inputs.registry_url          || 'ghcr.io' }}

    ########################
    # 2.  Steps            #
    ########################
    steps:
      - uses: actions/checkout@v3

      - name: Build & (optionally) push image
        run: |
          # --------------------------------------------------------------
          # Resolve working direc
